---
run:
  timeout: 3m
  build-tags:
    - integration
linters:
  enable:
    - misspell
    - goimports
    - revive
    - gofmt
    - depguard

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all # Matches all Go files, you can customize this as needed
        allow:
          - $gostd
          - github.com/spotahome/kooper/v2/controller
          - github.com/spotahome/kooper/v2/log
          - github.com/spotahome/kooper/v2/metrics/prometheus
          - github.com/sirupsen/logrus
          - github.com/prometheus/common/model
          - github.com/prometheus/prometheus/model/rulefmt
          - github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1
          - github.com/prometheus-operator/prometheus-operator/pkg/client/versioned
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - k8s.io/apimachinery/pkg/runtime
          - k8s.io/apimachinery/pkg/apis/meta/v1
          - k8s.io/client-go/tools/clientcmd
          - github.com/slok/sloth/internal/log
          - github.com/slok/sloth/internal/alert
          - github.com/slok/sloth/internal/prometheus
          - github.com/slok/sloth/internal/openslo
          - github.com/slok/sloth/pkg/kubernetes/api/sloth/v1
          - github.com/slok/sloth/pkg/prometheus/alertwindows/v1
          - github.com/slok/sloth/pkg/prometheus/plugin/v1
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by the standard library's errors package
  revive:
    rules:
      - name: unused-parameter
        disabled: true
        severity: warning
        exclude:
          - internal/log/log.go
          - test/integration/k8scontroller/plugin/plugin.go
          - internal/prometheus/sli_plugin.go
          - internal/prometheus/recording_rules.go
          - internal/openslo/spec.go
          - internal/k8sprometheus/storage_test.go
          - cmd/sloth/commands/k8scontroller.go
