---
run:
  timeout: 3m
  build-tags:
    - integration

issues:
  exclude-rules:
    - path: internal/log/log.go
      text: "unused-parameter: 'format' .*"
linters:
  enable:
    - misspell
    - goimports
    - revive
    - gofmt
    - depguard
    - godot
